export const KEYS = { 
    PROJECT_ID : import.meta.env.VITE_PROJECT_ID,
    DATABASE_FOODY_ID : import.meta.env.VITE_DATABASE_FOODY_ID,
    COLLECTION_MEALS_ID : import.meta.env.VITE_COLLECTION_MEALS_ID,
    COLLECTION_CUSTOMER_ID : import.meta.env.VITE_COLLECTION_CUSTOMER_ID,
 }
